server:
  port: ${PORT:8084}

spring:
  application:
    name: ms-payments
  datasource:
    url: JDBC:mysql://localhost:3306/ecofenix_payments?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ecofenix_temp
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}