server:
  port: ${PORT:8084}

spring:
  application:
    name: ms-payments
  datasource:
    url: jdbc:mysql://localhost:3306/ecofenix_payments?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ecofenix_temp
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true